generate_user_tree: generate_user_tree.c ../Data_models/node.c ../../Code/Data_models/user.c generate_message_tree generate_location_tree print_user_leaves print_message_leaves print_location_leaves
	gcc -g -o generate_user_tree generate_user_tree.c ../Data_models/node.c ../../Code/Data_models/user.c
generate_message_tree: generate_message_tree.c ../Data_models/node.c ../../Code/Data_models/message.c
	gcc -g -o generate_message_tree generate_message_tree.c ../Data_models/node.c ../../Code/Data_models/message.c
generate_location_tree: generate_location_tree.c ../Data_models/node.c ../../Code/Data_models/location.c
	gcc -g -o generate_location_tree generate_location_tree.c ../Data_models/node.c ../../Code/Data_models/location.c
print_user_leaves: print_user_leaves.c ../Data_models/node.c ../../Code/Data_models/user.c
	gcc -g -o print_user_leaves print_user_leaves.c ../Data_models/node.c ../../Code/Data_models/user.c
print_message_leaves: print_message_leaves.c ../Data_models/node.c ../../Code/Data_models/message.c
	gcc -g -o print_message_leaves print_message_leaves.c ../Data_models/node.c ../../Code/Data_models/message.c
print_location_leaves: print_location_leaves.c ../Data_models/node.c ../../Code/Data_models/location.c
	gcc -g -o print_location_leaves print_location_leaves.c ../Data_models/node.c ../../Code/Data_models/location.c


